services:
  mysql:
    image: mysql:8
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    platform: linux/amd64

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    env_file:
      - ./.env
    container_name: backend_prod
    ports:
      - "${SERVER_PORT}:3000"
    depends_on:
      - mysql

volumes:
  mysql-data-prod:
    driver: local