services:
  mysql:
    image: mysql:8
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    platform: linux/amd64

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./.env
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: backend
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - mysql
    command: npm run dev

volumes:
  mysql-data:
    driver: local